trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildAndTest
    displayName: Run Playwright Tests on Local Agent

    pool:
      name: 'MyAgentPool'  # Replace with your self-hosted agent pool name

    steps:
      # Step 1: Install Node.js dependencies
      - task: PowerShell@2
        displayName: 'Install dependencies'
        inputs:
          targetType: 'inline'
          script: |
            npm ci
            npm install playwright typescript ts-node mssql
          workingDirectory: tests/

      # Step 2: Install Playwright browsers
      - task: PowerShell@2
        displayName: 'Install Playwright browsers'
        inputs:
          targetType: 'inline'
          script: |
            npx playwright install
          workingDirectory: tests/

      # Step 3: Run Playwright tests
      - task: PowerShell@2
        displayName: 'Run Playwright tests'
        inputs:
          targetType: 'inline'
          script: |
            npx playwright test --reporter=html
          workingDirectory: tests/

      # Step 4: Publish Playwright HTML report as artifact
      - task: PublishPipelineArtifact@1
        displayName: 'Upload Playwright Report'
        inputs:
          targetPath: tests/playwright-report/
          artifact: 'Playwright tests'
          publishLocation: 'pipeline'
