trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildAndTest
    displayName: Run Playwright Tests on Local Agent

    pool:
      name: 'MyAgentPool'  # ✅ Use your self-hosted agent pool

    steps:
      # Step 1: Install dependencies
      - task: PowerShell@2
        displayName: 'Install NPM dependencies'
        inputs:
          targetType: 'inline'
          script: |
            npm ci
            npm install playwright allure-playwright typescript ts-node mssql
          workingDirectory: tests/

      # Step 2: Install Playwright browsers
      - task: PowerShell@2
        displayName: 'Install Playwright browsers'
        inputs:
          targetType: 'inline'
          script: |
            npx playwright install
          workingDirectory: tests/

      # Step 3: Run Playwright Tests with Allure Reporter
      - task: PowerShell@2
        displayName: 'Run Playwright tests'
        inputs:
          targetType: 'inline'
          script: |
            npx playwright test tests --reporter=line,allure-playwright
          workingDirectory: tests/

      # Step 4: Publish Allure Results (optional)
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Allure Results'
        inputs:
          targetPath: 'tests/allure-results'
          artifact: 'Allure Results'
          publishLocation: 'pipeline'
